version: '3'
services:
  datastore:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '80:80'
    networks:
      - machineLearningNet
networks:
  machineLearningNet:
