version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    networks:
      - machineLearningNet
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    networks:
      - machineLearningNet
  datastore:
    build: .
    links:
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - '80:80'
    networks:
      - machineLearningNet
networks:
  machineLearningNet:
