version: '3'
services:
  kafka:
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "wine_dev:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
