version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    networks:
      - machineLearningNet
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    networks:
      - machineLearningNet
  datastore:
    build: .
    links:
      - kafka
    ports:
      - '1337:80'
    networks:
      - machineLearningNet
    entrypoint: python -m app.datastore
  svc:
    build: .
    links:
      - kafka
    ports:
      - '1338:80'
    networks:
      - machineLearningNet
    entrypoint: python -m app.svc
  nearest_neighbor:
    build: .
    links:
      - kafka
    ports:
      - '1339:80'
    networks:
      - machineLearningNet
    entrypoint: python -m app.nearest_neighbor
networks:
  machineLearningNet:
