
swagger: '2.0'

info:
  title: datastore
  description: Manage data for machine learning services.
  version: '1.0.0'

host: datastore

schemes:
  - https

basePath: /v1

produces:
  - application/json

consumes:
  - application/json

paths:
  /wines:
    get:
      summary: Retrieve wine
      description: |
        This endpoint returns information of a wine record of a given id.
        The result indcludes all properties of the wine and its category.
      operationId: get_wine
      parameters:
        - name: wine_id
          in: query
          required: true
          type: string
      tags:
        - Wines
      responses:
        200:
          description: Wine and corresponding class
          schema:
            $ref: '#/definitions/ClassifiedWine'
        404:
          description: Unknown id
          schema:
            $ref: '#/definitions/Error'
        422:
          description: Malformed id
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected server error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Delete wine
      description: |
        This endpoint deletes a wine record of a given id.
      operationId: delete_wine
      parameters:
        - name: wine_id
          in: query
          required: true
          type: string
      tags:
        - Wines
      responses:
        204:
          description: Wine successfully deleted
        404:
          description: Unknown id
          schema:
            $ref: '#/definitions/Error'
        422:
          description: Malformed id
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected server error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create wine
      description: |
        This endpoint creates a wine record with a correspondening class.
      operationId: create_wine
      parameters:
        - name: classified_wine
          in: body
          required: true
          schema:
            $ref: '#/definitions/ClassifiedWine'
      tags:
        - Wines
      responses:
        201:
          description: Wine successfully created
          schema:
            type: object
            properties:
              id:
                type: string
        422:
          description: Validation error of parameter
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected server error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Wine:
    type: object
    required:
      - alcohol
      - malic_acid
      - ash
      - alcalinity_of_ash
      - magnesium
      - total_phenols
      - flavanoids
      - nonflavanoid_phenols
      - proanthocyanins
      - color_intensity
      - hue
      - odxxx_of_diluted_wines
      - proline
    properties:
      alcohol:
        type: number
        format: float
        minimum: 0.0
      malic_acid:
        type: number
        format: float
        minimum: 0.0
      ash:
        type: number
        format: float
        minimum: 0.0
      alcalinity_of_ash:
        type: number
        format: float
        minimum: 0.0
      magnesium:
        type: integer
        format: int32
        minimum: 0
      total_phenols:
        type: number
        format: float
        minimum: 0.0
      flavanoids:
        type: number
        format: float
        minimum: 0.0
      nonflavanoid_phenols:
        type: number
        format: float
        minimum: 0.0
      proanthocyanins:
        type: number
        format: float
        minimum: 0.0
      color_intensity:
        type: number
        format: float
        minimum: 0.0
      hue:
        type: number
        format: float
        minimum: 0.0
      odxxx_of_diluted_wines:
        type: number
        format: float
        minimum: 0.0
        description: OD280/OD315 of diluted wines
      proline:
        type: integer
        format: int32
        minimum: 0
  ClassifiedWine:
    type: object
    required:
      - wine
      - class
    properties:
      wine:
        $ref: '#/definitions/Wine'
      class:
        type: integer
        format: int32
        minimum: 1
        maximum: 3
        description: Class of the wine. Valid values are 1-3.
  Error:
    type: object
    required:
      - code
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
